# Generated by Django 6.0.3 on 2026-04-11 06:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('MENTOR', 'Mentor'), ('FITNESS', 'Fitness'), ('TEACHER', 'Teacher'), ('CONSULTANT', 'Consultant'), ('DOCTOR', 'Doctor')], default='MENTOR', max_length=20)),
                ('team_size', models.CharField(choices=[('JUST_ME', 'Just Me'), ('SMALL', 'Small (2-10)'), ('MEDIUM', 'Medium (11-50)'), ('LARGE', 'Large (51-200)'), ('ENTERPRISE', 'Enterprise (200+)')], default='JUST_ME', max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace_type', models.CharField(choices=[('solo', 'Solo'), ('team', 'Team')], default='solo', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tenants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('PROFESSIONAL', 'Professional')], db_index=True, default='PROFESSIONAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_members',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['tenant', 'user'], name='tenant_memb_tenant__87befd_idx'), models.Index(fields=['user'], name='tenant_memb_user_id_a9175b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('tenant', 'user'), name='unique_active_tenant_user')],
            },
        ),
    ]
