# Generated by Django 5.2.4 on 2026-02-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tenant_type', models.CharField(choices=[('DOCTOR', 'Doctor'), ('MENTOR', 'Mentor'), ('FREELANCER', 'Freelancer'), ('TEACHER', 'Teacher'), ('COMPANY', 'Company')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
