# Generated by Django 5.2.4 on 2026-03-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmember',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
