# Generated by Django 5.2.4 on 2026-03-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantmember_removed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='team_size',
        ),
        migrations.AddField(
            model_name='tenant',
            name='workspace_type',
            field=models.CharField(choices=[('SOLO', 'Solo'), ('TEAM', 'Team')], default='SOLO', max_length=10),
        ),
    ]
