# Generated by Django 5.2.4 on 2026-03-03 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remove_tenant_team_size_tenant_workspace_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenantmember',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tenantmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('PROFESSIONAL', 'professional')], db_index=True, default='PROFESSIONAL', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='tenantmember',
            constraint=models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('tenant', 'user'), name='unique_active_tenant_user'),
        ),
    ]
