# Generated by Django 5.2.4 on 2026-03-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenantmember_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='team_size',
            field=models.CharField(choices=[('JUST_ME', 'Just Me'), ('SMALL', 'Small (2-10)'), ('MEDIUM', 'Medium (11-50)'), ('LARGE', 'Large (51-200)'), ('ENTERPRISE', 'Enterprise (200+)')], default='JUST_ME', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('PROFESSIONAL', 'Professional')], db_index=True, default='PROFESSIONAL', max_length=20),
        ),
    ]
