# Generated by Django 5.2.11 on 2026-03-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_team_size_alter_tenantmember_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='tenant_type',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='workspace_type',
        ),
        migrations.AddField(
            model_name='tenant',
            name='template_type',
            field=models.CharField(choices=[('MENTOR', 'Mentor'), ('FITNESS', 'Fitness'), ('TEACHER', 'Teacher'), ('CONSULTANT', 'Consultant')], default='MENTOR', max_length=20),
        ),
    ]
