# Generated by Django 5.2.11 on 2026-04-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_remove_tenant_tenant_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='workspace_type',
            field=models.CharField(choices=[('solo', 'Solo'), ('team', 'Team')], default='solo', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='template_type',
            field=models.CharField(choices=[('MENTOR', 'Mentor'), ('FITNESS', 'Fitness'), ('TEACHER', 'Teacher'), ('CONSULTANT', 'Consultant'), ('DOCTOR', 'Doctor')], default='MENTOR', max_length=20),
        ),
    ]
