# Generated by Django 5.2.13 on 2026-04-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('professional', 'Professional'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
