# Generated by Django 5.2.4 on 2026-02-24 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('linkdin_url', models.URLField(blank=True, null=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'professional_profiles',
                'indexes': [models.Index(fields=['user'], name='professiona_user_id_f93863_idx'), models.Index(fields=['verified'], name='professiona_verifie_25c916_idx')],
            },
        ),
    ]
