# Generated by Django 5.2.13 on 2026-04-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('professional', 'Professional'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
