# Generated by Django 5.2.13 on 2026-05-13 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_active_provider_booking_slot',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status__in', ['PENDING', 'CONFIRMED'])), fields=('provider', 'date', 'start_time'), name='unique_active_provider_booking_slot'),
        ),
    ]
