# Generated by Django 5.2.13 on 2026-05-19 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='bookinghistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_active_provider_booking_slot',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='service',
            name='provider',
        ),
        migrations.AddField(
            model_name='availability',
            name='buffer_after',
            field=models.PositiveIntegerField(default=0, help_text='Buffer after booking in minutes'),
        ),
        migrations.AddField(
            model_name='availability',
            name='buffer_before',
            field=models.PositiveIntegerField(default=0, help_text='Buffer before booking in minutes'),
        ),
        migrations.AddField(
            model_name='availability',
            name='max_bookings_per_slot',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CARD', 'Card'), ('UPI', 'UPI'), ('CASH', 'Cash')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='date_specific',
            field=models.DateField(blank=True, help_text='Overrides recurring availability', null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='slot_duration',
            field=models.PositiveIntegerField(help_text='Slot duration in minutes'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_source',
            field=models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile'), ('ADMIN', 'Admin')], default='WEB', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('PARTIAL_REFUND', 'Partial Refund')], default='UNPAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('PROCESSED', 'Processed')], default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING_PAYMENT', max_length=30),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='new_status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], max_length=30),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='previous_status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], max_length=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['tenant'], name='booking_ava_tenant__e4c77a_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['service'], name='booking_ava_service_3949f3_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['user'], name='booking_ava_user_id_7e846a_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['day_of_week'], name='booking_ava_day_of__704462_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['date_specific'], name='booking_ava_date_sp_dbb43c_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['is_active'], name='booking_ava_is_acti_e675f5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='booking_boo_created_274495_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['is_deleted'], name='booking_boo_is_dele_8d5ade_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['tenant'], name='booking_ser_tenant__bfe92e_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='booking_ser_is_acti_c0a5c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='booking_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status__in', ['PENDING_PAYMENT', 'CONFIRMED'])), fields=('provider', 'date', 'start_time'), name='unique_active_provider_booking_slot'),
        ),
    ]
