# Generated by Django 5.2.13 on 2026-05-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_unique_active_provider_booking_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('PROVIDER', 'Provider'), ('ADMIN', 'Admin')], max_length=20, null=True),
        ),
    ]
