# Generated by Django 5.2.13 on 2026-04-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_availability_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='date_specific',
            field=models.DateField(blank=True, help_text='Overrides day_of_week if set', null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
    ]
