# Generated by Django 5.2.13 on 2026-05-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='attendance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('checked_in', 'Checked In'), ('no_show', 'No Show')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
