# Generated by Django 5.2.4 on 2026-03-10 05:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans_subsci', '0001_initial'),
        ('tenants', '0005_tenant_team_size_alter_tenantmember_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plans',
            old_name='isactive_plan',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='plans',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plans',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='plans',
            name='razorpay_plan_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='member_limit',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans_subsci.plans'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant'),
        ),
    ]
