# Generated by Django 5.2.4 on 2026-03-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans_subsci', '0002_rename_isactive_plan_plans_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='plans',
            name='booking_limit',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='addons',
            field=models.ManyToManyField(blank=True, to='plans_subsci.addon'),
        ),
    ]
