# Generated by Django 5.2.4 on 2026-03-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantinvitation',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('PROFESSIONAL', 'Professional')], default='PROFESSIONAL', max_length=20),
        ),
    ]
