# Generated by Django 5.2.4 on 2026-02-20 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantinvitation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='tenantinvitation',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='tenantinvitation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
